names = [ "Leri" , "Luka" , "beqa" , "Nika" , "Misho" , "ladi" , "mariam" , "ana" , "nino" , "sandro" ]
print (f" these are the names of my friends: {names[0]} , {names[1]} , {names[2].title()} , {names[3]} , {names[4]} , {names[5].title()} , {names[6].title()} , {names[7].title()} , {names[8].title()} , {names[9].title()}")
# in this code I made an intentional error
# I will try to access an index that is out of range
# this will raise an IndexError
# Uncomment the line below to see the error
# print ({names[-11]})